# Model Building

## Attaching Resources

### Importing Necessary Libraries

In [5]:
import numpy as np
import pandas as pd
from sklearn.metrics import pairwise_distances
import pickle

import warnings

warnings.filterwarnings('ignore')

### Adding Dataset

#### Area

In [6]:
area=pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\GitHub\Book_Recommendation\Data Preprocessing & EDA\Area.csv")

area

         User-ID         ISBN  Book-Rating    country
0         276725   034545104X            0        usa
1         276726   0155061224            5        usa
2         276727   0446520802            0  australia
3         276729   052165615X            3    croatia
4         276729   0521795028            6    croatia
...          ...          ...          ...        ...
1149775   276704   1563526298            9        usa
1149776   276706   0679447156            0     canada
1149777   276709   0515107662           10        usa
1149778   276721   0590442449           10        usa
1149779   276723  05162443314            8        usa

[1149780 rows x 4 columns]

In [7]:
count_area = pd.DataFrame(
        {
            'INDEX' : area['User-ID'].value_counts().index,
            'COUNT' : area['User-ID'].value_counts().values
        }
    )

count_area

         INDEX  COUNT
0        11676  13602
1       198711   7550
2       153662   6109
3        98391   5891
4        35859   5850
...        ...    ...
105278  116180      1
105279  116166      1
105280  116154      1
105281  116137      1
105282  276723      1

[105283 rows x 2 columns]

In [8]:
d_area = count_area[count_area['COUNT'] < 100].loc[:,'INDEX'].values

In [9]:
drop_area = []

for i in range(len(d_area)):
    for j in area[area['User-ID'] == d_area[i]].index:
        drop_area.append(j)

In [10]:
area.drop(index=drop_area, inplace=True)

area

         User-ID        ISBN  Book-Rating country
412       276925  0006511929            0   spain
413       276925  002542730X           10   spain
414       276925  0060520507            0   spain
415       276925  0060930934            0   spain
416       276925  0060951303            0   spain
...          ...         ...          ...     ...
1149633   276680  1884910033            0     usa
1149634   276680  1888173408            7     usa
1149635   276680  1888173564            8     usa
1149636   276680  1888173572            0     usa
1149637   276680  1931561648            9     usa

[658805 rows x 4 columns]

#### Age

In [11]:
age=pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\GitHub\Book_Recommendation\Data Preprocessing & EDA\Age.csv")

age

         User-ID         ISBN  Book-Rating   Age_Type
0         276725   034545104X            0      Other
1         276726   0155061224            5      Other
2         276727   0446520802            0   Teenager
3         276729   052165615X            3   Teenager
4         276729   0521795028            6   Teenager
...          ...          ...          ...        ...
1149775   276704   1563526298            9      Other
1149776   276706   0679447156            0  Youngster
1149777   276709   0515107662           10      Adult
1149778   276721   0590442449           10   Teenager
1149779   276723  05162443314            8   Children

[1149780 rows x 4 columns]

In [12]:
count_age = pd.DataFrame(
        {
            'INDEX' : age['User-ID'].value_counts().index,
            'COUNT' : age['User-ID'].value_counts().values
        }
    )

count_age

         INDEX  COUNT
0        11676  13602
1       198711   7550
2       153662   6109
3        98391   5891
4        35859   5850
...        ...    ...
105278  116180      1
105279  116166      1
105280  116154      1
105281  116137      1
105282  276723      1

[105283 rows x 2 columns]

In [13]:
d_age = count_age[count_age['COUNT'] < 100].loc[:,'INDEX'].values

In [14]:
drop_age = []

for i in range(len(d_age)):
    for j in age[age['User-ID'] == d_age[i]].index:
        drop_age.append(j)

In [15]:
age.drop(index=drop_age, inplace=True)

age

         User-ID        ISBN  Book-Rating   Age_Type
412       276925  0006511929            0  Youngster
413       276925  002542730X           10  Youngster
414       276925  0060520507            0  Youngster
415       276925  0060930934            0  Youngster
416       276925  0060951303            0  Youngster
...          ...         ...          ...        ...
1149633   276680  1884910033            0      Adult
1149634   276680  1888173408            7      Adult
1149635   276680  1888173564            8      Adult
1149636   276680  1888173572            0      Adult
1149637   276680  1931561648            9      Adult

[658805 rows x 4 columns]

## Preparing Model From The Dataset

### Preparing Model Based On Area

#### usa

In [ ]:
area1=area[area['country']=='usa']
area1

         User-ID        ISBN  Book-Rating country
1456      277427  002542730X           10     usa
1457      277427  0026217457            0     usa
1458      277427  003008685X            8     usa
1459      277427  0030615321            0     usa
1460      277427  0060002050            0     usa
...          ...         ...          ...     ...
1149633   276680  1884910033            0     usa
1149634   276680  1888173408            7     usa
1149635   276680  1888173564            8     usa
1149636   276680  1888173572            0     usa
1149637   276680  1931561648            9     usa

[474698 rows x 4 columns]

In [ ]:
area1['Book-Rating'].unique()

array([10,  0,  8,  7,  9,  6,  5,  4,  2,  3,  1], dtype=int64)

In [ ]:
area1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 474698 entries, 1456 to 1149637
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   User-ID      474698 non-null  int64
 1   ISBN         474698 non-null  object
 2   Book-Rating  474698 non-null  int64
 3   country      474698 non-null  object
dtypes: int64(2), object(2)
memory usage: 18.1+ MB

In [ ]:
usa = area1.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
usa.fillna(0,inplace = True)

usa

ISBN,0375404120,*0515128325,0000000051,0000001042283,0000018030,0001047868,0001048759,0001052276,0001053736,0001053744,...,SBN67001026X,T110105305048,T110105705048,TBR0385495641,THEALLTRUETRA,THECATASTROPH,THEFLYINGACE,"YOUTELLEM,AND",b00005wz75,Ô½crosoft
User-ID,,,,,,,,,,,,,,,,,,,,,
254,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
507,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1435,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1733,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278188,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278418,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
usa_similarity = 1 - pairwise_distances(usa,metric='cosine')
np.fill_diagonal(usa_similarity,0)

usa_similarity = pd.DataFrame(usa_similarity)
usa_similarity.index = np.sort(area1['User-ID'].unique())
usa_similarity.columns = np.sort(area1['User-ID'].unique())

usa_similarity

,254,507,882,1435,1733,2033,2110,2276,2358,2766,...,274808,275020,275970,276463,276680,277427,277639,278137,278188,278418
254,0.000000,0.030295,0.023211,0.000000,0.000000,0.052825,0.000000,0.000000,0.0,0.000000,...,0.00000,0.0,0.012727,0.025349,0.016365,0.000000,0.0,0.0,0.0,0.0
507,0.030295,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.032066,0.0,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
882,0.023211,0.000000,0.000000,0.000000,0.010862,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.0,0.000000,0.000000,0.040752,0.020002,0.0,0.0,0.0,0.0
1435,0.000000,0.000000,0.000000,0.000000,0.001383,0.000000,0.000000,0.000000,0.0,0.007951,...,0.05544,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
1733,0.000000,0.000000,0.010862,0.001383,0.000000,0.000000,0.016085,0.000000,0.0,0.001095,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,0.000000,0.000000,0.020002,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.020162,...,0.00000,0.0,0.006398,0.000000,0.029510,0.000000,0.0,0.0,0.0,0.0
277639,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.023342,0.0,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
278137,0.000000,0.000000,0.000000,0.000000,0.000000,0.005546,0.000000,0.000000,0.0,0.000000,...,0.00000,0.0,0.012370,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
278188,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
278418,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.006667,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0

In [ ]:
usa_similarity1 = pd.DataFrame(
    {
        'user-1' : usa_similarity.idxmax().index,
        'user-2' : usa_similarity.idxmax().values
    }
)

usa_similarity1

      user-1  user-2
0        254   88122
1        507   37712
2        882  149084
3       1435  264543
4       1733  180917
...      ...     ...
1187  277427  224340
1188  277639  240035
1189  278137   31040
1190  278188  218569
1191  278418  170742

[1192 rows x 2 columns]

#### canada

In [ ]:
area2=area[area['country']=='canada']
area2

         User-ID        ISBN  Book-Rating country
25448       6242  0002244098            5  canada
25449       6242  0006385370            7  canada
25450       6242  0006391761            6  canada
25451       6242  0006392237            7  canada
25452       6242  0006480608            7  canada
...          ...         ...          ...     ...
1128315   270713  1895897645            0  canada
1128316   270713  1896239684            0  canada
1128317   270713  1930051220            0  canada
1128318   270713  1931412065            0  canada
1128319   270713  O67174142X            8  canada

[59333 rows x 4 columns]

In [ ]:
area2['Book-Rating'].unique()

array([ 5,  7,  6,  0,  8,  3,  4, 10,  9,  1,  2], dtype=int64)

In [ ]:
area2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59333 entries, 25448 to 1128319
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      59333 non-null  int64
 1   ISBN         59333 non-null  object
 2   Book-Rating  59333 non-null  int64
 3   country      59333 non-null  object
dtypes: int64(2), object(2)
memory usage: 2.3+ MB

In [ ]:
canada = area2.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
canada.fillna(0,inplace = True)

canada

ISBN,0000913154,000104799X,0001055607,0001251782,0001382381,0001382608,0001840517,0001961721,0002000288,0002000474,...,JaneDentinger,LATITUDESOFME,N006485332,O590477412,O67174142X,O774037474,O77O428452,O880015152,O889950962,Q380708353
User-ID,,,,,,,,,,,,,,,,,,,,,
6242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8782,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9417,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16721,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
268300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
268932,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
270554,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
270713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
canada_similarity = 1 - pairwise_distances(canada,metric='cosine')
np.fill_diagonal(canada_similarity,0)

canada_similarity = pd.DataFrame(canada_similarity)
canada_similarity.index = np.sort(area2['User-ID'].unique())
canada_similarity.columns = np.sort(area2['User-ID'].unique())

canada_similarity

,6242,8782,9417,14456,16721,16966,21404,23288,26583,27617,...,260183,263325,263877,264321,265889,266522,268300,268932,270554,270713
6242,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.014166,0.000000,0.008635,0.000000,...,0.006700,0.076761,0.009412,0.013856,0.016795,0.0,0.000000,0.018002,0.086139,0.049439
8782,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.021957,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.013587
9417,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.027912,0.000000,0.000000,0.000000,...,0.000000,0.022453,0.016690,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.011433
14456,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.023019,0.000000,0.000000,0.000000,0.000000,0.0,0.033215,0.012193,0.000000,0.007928
16721,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266522,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.021489,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
268300,0.000000,0.000000,0.000000,0.033215,0.0,0.008803,0.000000,0.000000,0.000000,0.012788,...,0.008216,0.012420,0.000000,0.016127,0.000000,0.0,0.000000,0.000000,0.000000,0.004304
268932,0.018002,0.000000,0.000000,0.012193,0.0,0.000000,0.000000,0.011119,0.000000,0.000000,...,0.000000,0.012260,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.014537,0.010242
270554,0.086139,0.000000,0.000000,0.000000,0.0,0.000000,0.039234,0.000000,0.000000,0.017476,...,0.018946,0.117486,0.021028,0.046437,0.019087,0.0,0.000000,0.014537,0.000000,0.040962
270713,0.049439,0.013587,0.011433,0.007928,0.0,0.000000,0.007433,0.000000,0.000000,0.009120,...,0.012695,0.035431,0.008642,0.027767,0.002792,0.0,0.004304,0.010242,0.040962,0.000000

In [ ]:
canada_similarity1 = pd.DataFrame(
    {
        'user-1' : canada_similarity.idxmax().index,
        'user-2' : canada_similarity.idxmax().values
    }
)

usa_similarity1

      user-1  user-2
0        254   88122
1        507   37712
2        882  149084
3       1435  264543
4       1733  180917
...      ...     ...
1187  277427  224340
1188  277639  240035
1189  278137   31040
1190  278188  218569
1191  278418  170742

[1192 rows x 2 columns]

#### united kingdom

In [ ]:
area3=area[area['country']=='unitedkingdom']
area3

         User-ID        ISBN  Book-Rating        country
29970       7105  0006176917            0  unitedkingdom
29971       7105  0006372570            5  unitedkingdom
29972       7105  0006374093            0  unitedkingdom
29973       7105  0006482880            0  unitedkingdom
29974       7105  0006548717            3  unitedkingdom
...          ...         ...          ...            ...
1137218   273718  1869928318           10  unitedkingdom
1137219   273718  1871592232           10  unitedkingdom
1137220   273718  189830713X           10  unitedkingdom
1137221   273718  1904492355            0  unitedkingdom
1137222   273718  3822862142            9  unitedkingdom

[26139 rows x 4 columns]

In [ ]:
area3['Book-Rating'].unique()

array([ 0,  5,  3,  6,  9,  7, 10,  8,  4,  1,  2], dtype=int64)

In [ ]:
area3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26139 entries, 29970 to 1137222
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      26139 non-null  int64
 1   ISBN         26139 non-null  object
 2   Book-Rating  26139 non-null  int64
 3   country      26139 non-null  object
dtypes: int64(2), object(2)
memory usage: 1021.1+ KB

In [ ]:
unitedkingdom = area3.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
unitedkingdom.fillna(0,inplace = True)

unitedkingdom

ISBN,0*708880258,0000000026307,0000000029841,0000000030670,0000000033220,0000000124911,0000001056518,0001010565,0001046438,000104687X,...,CN109567,CN110912,CN115072,CN124650,CN9944/1142,L583225846,O856856428,O861366301,cn108465,cn113107
User-ID,,,,,,,,,,,,,,,,,,,,,
7105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25533,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30509,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266866,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
269728,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
272225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
273718,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
unitedkingdom_similarity = 1 - pairwise_distances(unitedkingdom,metric='cosine')
np.fill_diagonal(unitedkingdom_similarity,0)

unitedkingdom_similarity = pd.DataFrame(unitedkingdom_similarity)
unitedkingdom_similarity.index = np.sort(area3['User-ID'].unique())
unitedkingdom_similarity.columns = np.sort(area3['User-ID'].unique())

unitedkingdom_similarity

,7105,23902,25533,30509,30712,33888,37567,40647,44925,56271,...,238864,244277,246156,246617,252827,261037,266866,269728,272225,273718
7105,0.000000,0.000000,0.000000,0.0,0.017018,0.036755,0.000000,0.000000,0.00000,0.011463,...,0.052992,0.021861,0.000000,0.011626,0.022752,0.000000,0.000000,0.010238,0.0,0.022771
23902,0.000000,0.000000,0.010436,0.0,0.008272,0.005360,0.003555,0.000000,0.00000,0.005474,...,0.014342,0.000577,0.006422,0.003992,0.002524,0.014567,0.001374,0.001352,0.0,0.011836
25533,0.000000,0.010436,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.021522,...,0.032618,0.000000,0.000000,0.024697,0.000000,0.021310,0.000000,0.016659,0.0,0.000000
30509,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
30712,0.017018,0.008272,0.000000,0.0,0.000000,0.011112,0.014739,0.034013,0.02755,0.000000,...,0.000000,0.000000,0.000000,0.022918,0.010853,0.011884,0.000000,0.009966,0.0,0.012414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261037,0.000000,0.014567,0.021310,0.0,0.011884,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.026079,0.000000,0.000000,0.000000,0.0,0.000000
266866,0.000000,0.001374,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.040633,...,0.032900,0.000000,0.000000,0.000000,0.008779,0.000000,0.000000,0.025958,0.0,0.000000
269728,0.010238,0.001352,0.016659,0.0,0.009966,0.000000,0.000000,0.000000,0.00000,0.006484,...,0.045313,0.000000,0.016950,0.012860,0.000000,0.000000,0.025958,0.000000,0.0,0.000000
272225,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.014338,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
273718,0.022771,0.011836,0.000000,0.0,0.012414,0.016521,0.000000,0.000000,0.00000,0.013668,...,0.026136,0.031007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [ ]:
unitedkingdom_similarity1 = pd.DataFrame(
    {
        'user-1' : unitedkingdom_similarity.idxmax().index,
        'user-2' : unitedkingdom_similarity.idxmax().values
    }
)

unitedkingdom_similarity1

    user-1  user-2
0     7105  238864
1    23902  209516
2    25533   92853
3    30509    7105
4    30712  124688
..     ...     ...
81  261037   60797
82  266866   72451
83  269728  238864
84  272225  100088
85  273718  114446

[86 rows x 2 columns]

#### australia

In [ ]:
area4=area[area['country']=='australia']
area4

         User-ID        ISBN  Book-Rating    country
12725       1424  0007119860            0  australia
12726       1424  0060000805            7  australia
12727       1424  0060505273            0  australia
12728       1424  0060512822            7  australia
12729       1424  0060730552            9  australia
...          ...         ...          ...        ...
1140652   274301  1879237806           10  australia
1140653   274301  1886913439            0  australia
1140654   274301  9994770934           10  australia
1140655   274301  9998914140           10  australia
1140656   274301  B00009NDAN           10  australia

[13575 rows x 4 columns]

In [ ]:
area4['Book-Rating'].unique()

array([ 0,  7,  9,  8,  5,  6, 10,  4,  3,  1,  2], dtype=int64)

In [ ]:
area4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13575 entries, 12725 to 1140656
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      13575 non-null  int64
 1   ISBN         13575 non-null  object
 2   Book-Rating  13575 non-null  int64
 3   country      13575 non-null  object
dtypes: int64(2), object(2)
memory usage: 530.3+ KB

In [ ]:
australia = area4.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
australia.fillna(0,inplace = True)

australia

ISBN,0 00 614494 2,0 85550 000 x,0000000000000,0000001481,0001033085,0001047663,0001048082,0001049879,0001604163,0001604465,...,B0000523SS,B000055Z5S,B00005N5J6,B00005WAEO,B00005X0HL,B0000646QD,B00008NRHQ,B00009NDAN,B0002JV9PY,B0002K6K8O
User-ID,,,,,,,,,,,,,,,,,,,,,
1424,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98787,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99227,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109901,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109955,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112541,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
113817,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
114865,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118434,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121726,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141819,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149690,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
155916,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161936,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168387,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
172248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
175886,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
176062,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
179791,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
180707,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
180957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
183958,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
203280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
214528,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
216882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
220867,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
222716,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225232,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
231857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
233711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
236340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0
241204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
246671,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
246776,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
256247,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
259378,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
262902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
262998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
274301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0

In [ ]:
australia_similarity = 1 - pairwise_distances(australia,metric='cosine')
np.fill_diagonal(australia_similarity,0)

australia_similarity = pd.DataFrame(australia_similarity)
australia_similarity.index = np.sort(area4['User-ID'].unique())
australia_similarity.columns = np.sort(area4['User-ID'].unique())

australia_similarity

,1424,13995,15957,16161,16943,30711,42400,44296,53729,79942,...,233711,236340,241204,246671,246776,256247,259378,262902,262998,274301
1424,0.000000,0.015391,0.027016,0.017772,0.000000,0.011629,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.045859,0.000000,0.025029,0.030255,0.006322,0.000000
13995,0.015391,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.024298,0.000000,...,0.000000,0.000000,0.014216,0.0,0.000000,0.000000,0.027720,0.000000,0.010287,0.000000
15957,0.027016,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.024490,0.000000,...,0.035814,0.000000,0.065972,0.0,0.000000,0.078517,0.000000,0.000000,0.010157,0.037237
16161,0.017772,0.000000,0.000000,0.000000,0.000000,0.011154,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.023458,0.000000,0.000000,0.015873,0.009913,0.000000
16943,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.027149,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30711,0.011629,0.000000,0.000000,0.011154,0.000000,0.000000,0.0,0.017003,0.000000,0.000000,...,0.021316,0.004222,0.000000,0.0,0.032405,0.014787,0.000000,0.025196,0.003967,0.007382
42400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44296,0.000000,0.000000,0.000000,0.000000,0.000000,0.017003,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.010701
53729,0.000000,0.024298,0.024490,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.012544,0.018618,0.0,0.000000,0.000000,0.048620,0.021700,0.000000,0.000000
79942,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.023211,0.000000,0.000000,0.0,0.000000,0.022617,0.000000,0.000000,0.009875,0.000000
86033,0.000000,0.000000,0.000000,0.000000,0.000000,0.018704,0.0,0.000000,0.000000,0.000000,...,0.013752,0.000000,0.000000,0.0,0.000000,0.018216,0.000000,0.000000,0.000000,0.000000
86202,0.000000,0.000000,0.057699,0.000000,0.000000,0.083013,0.0,0.000000,0.020361,0.000000,...,0.018012,0.012684,0.031466,0.0,0.000000,0.099038,0.026547,0.034480,0.013866,0.019010
98787,0.016035,0.000000,0.000000,0.021971,0.000000,0.040255,0.0,0.000000,0.000000,0.000000,...,0.031492,0.022786,0.017774,0.0,0.000000,0.000000,0.049509,0.020716,0.000000,0.020357
99227,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.033519,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
109901,0.045382,0.000000,0.020249,0.000000,0.022204,0.000000,0.0,0.012635,0.012393,0.016149,...,0.000000,0.015220,0.000000,0.0,0.000000,0.000000,0.016415,0.024803,0.002073,0.039534
109955,0.000000,0.000000,0.000000,0.000000,0.000000,0.008003,0.0,0.014732,0.000000,0.000000,...,0.000000,0.017488,0.000000,0.0,0.020780,0.000000,0.000000,0.000000,0.000000,0.000000
112541,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.010011,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
113817,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.029767,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
114865,0.000000,0.000000,0.000000,0.000000,0.018422,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.003660,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
118434,0.030151,0.000000,0.000000,0.028918,0.000000,0.031538,0.0,0.000000,0.000000,0.000000,...,0.016119,0.000000,0.000000,0.0,0.039798,0.000000,0.000000,0.000000,0.010286,0.000000
121726,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.025067,0.000000,0.000000,0.000000,0.000000
123625,0.000000,0.000000,0.000000,0.000000,0.000000,0.010262,0.0,0.000000,0.000000,0.000000,...,0.025913,0.011080,0.000000,0.0,0.000000,0.000000,0.000000,0.019168,0.000000,0.000000
141819,0.000000,0.000000,0.000000,0.000000,0.000000,0.012748,0.0,0.010266,0.000000,0.000000,...,0.014479,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
144131,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
145165,0.000000,0.000000,0.000000,0.000000,0.000000,0.029448,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.035494,0.025460,0.000000,0.000000
149690,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.032094,0.000000,...,0.007887,0.013995,0.000000,0.0,0.036347,0.000000,0.032546,0.035018,0.000000,0.000000
155916,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
157655,0.043591,0.000000,0.043855,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.038456,0.000000,0.0,0.000000,0.000000,0.031107,0.000000,0.010262,0.000000
161936,0.035796,0.000000,0.000000,0.018311,0.000000,0.035778,0.0,0.000000,0.000000,0.000000,...,0.017011,0.006160,0.000000,0.0,0.072798,0.023975,0.029011,0.019183,0.006513,0.000000
168387,0.000000,0.000000,0.047065,0.000000,0.000000,0.000000,0.0,0.025379,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
172248,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
175886,0.000000,0.000000,0.000000,0.000000,0.000000,0.050991,0.0,0.000000,0.000000,0.000000,...,0.041804,0.000000,0.000000,0.0,0.000000,0.000000,0.060650,0.108134,0.000000,0.000000
176062,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.041865,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
179791,0.000000,0.000000,0.000000,0.000000,0.000000,0.015020,0.0,0.000000,0.031047,0.000000,...,0.000000,0.008703,0.000000,0.0,0.017581,0.000000,0.000000,0.000000,0.000000,0.009511
180707,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
180957,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.016369,0.010512,0.000000,0.000000,0.000000,0.000000
183958,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.009245,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.011263,0.000000,0.000000
203280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.026746,0.000000,...,0.000000,0.031656,0.000000,0.0,0.000000,0.000000,0.000000,0.029183,0.000000,0.034595
214528,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
216882,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.025783,...,0.000000,0.000000,0.000000,0.0,0.032014,0.000000,0.000000,0.000000,0.000000,0.000000
220867,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.080790,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.015809,0.000000
222716,0.000000,0.000000,0.000000,0.000000,0.065079,0.014903,0.0,0.000000,0.000000,0.000000,...,0.028564,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.035790,0.000000,0.000000
225232,0.000000,0.000000,0.045961,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.006292,0.000000,0.000000,0.0,0.011651,0.011085,0.009273,0.000000,0.017303,0.004980
231857,0.009422,0.000000,0.000000,0.000000,0.000000,0.014642,0.0,0.000000,0.016734,0.046606,...,0.000000,0.005212,0.000000,0.0,0.000000,0.020284,0.014848,0.000000,0.000000,0.025632
233711,0.000000,0.000000,0.035814,0.000000,0.027149,0.021316,0.0,0.000000,0.000000,0.023211,...,0.000000,0.052864,0.000000,0.0,0.000000,0.021593,0.000000,0.012798,0.005587,0.000000
236340,0.000000,0.000000,0.000000,0.000000,0.000000,0.004222,0.0,0.000000,0.012544,0.000000,...,0.052864,0.000000,0.000000,0.0,0.014206,0.000000,0.014538,0.000000,0.004196,0.140903
241204,0.000000,0.014216,0.065972,0.000000,0.000000,0.000000,0.0,0.000000,0.018618,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
246671,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
246776,0.045859,0.000000,0.000000,0.023458,0.000000,0.032405,0.0,0.000000,0.000000,0.000000,...,0.000000,0.014206,0.000000,0.0,0.000000,0.040953,0.000000,0.024576,0.008344,0.000000
256247,0.000000,0.000000,0.078517,0.000000,0.000000,0.014787,0.0,0.000000,0.000000,0.022617,...,0.021593,0.000000,0.000000,0.0,0.040953,0.000000,0.000000,0.000000,0.006124,0.000000
259378,0.025029,0.027720,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.048620,0.000000,...,0.000000,0.014538,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
262902,0.030255,0.000000,0.000000,0.015873,0.000000,0.025196,0.0,0.000000,0.021700,0.000000,...,0.012798,0.000000,0.000000,0.0,0.024576,0.000000,0.000000,0.000000,0.000000,0.007239
262998,0.006322,0.010287,0.010157,0.009913,0.000000,0.003967,0.0,0.000000,0.000000,0.009875,...,0.005587,0.004196,0.000000,0.0,0.008344,0.006124,0.000000,0.000000,0.000000,0.002866
274301,0.000000,0.000000,0.037237,0.000000,0.000000,0.007382,0.0,0.010701,0.000000,0.000000,...,0.000000,0.140903,0.000000,0.0,0.000000,0.000000,0.000000,0.007239,0.002866,0.000000

In [ ]:
australia_similarity1 = pd.DataFrame(
    {
        'user-1' : australia_similarity.idxmax().index,
        'user-2' : australia_similarity.idxmax().values
    }
)

australia_similarity1

    user-1  user-2
0     1424  246776
1    13995  259378
2    15957  256247
3    16161  118434
4    16943  222716
5    30711   86202
6    42400    1424
7    44296  168387
8    53729  259378
9    79942  220867
10   86033  145165
11   86202   98787
12   98787   86202
13   99227  220867
14  109901    1424
15  109955  246776
16  112541  149690
17  113817   86202
18  114865   16943
19  118434  161936
20  121726  256247
21  123625  149690
22  141819  233711
23  144131    1424
24  145165  222716
25  149690  123625
26  155916    1424
27  157655   15957
28  161936  246776
29  168387  176062
30  172248    1424
31  175886  262902
32  176062  168387
33  179791   53729
34  180707    1424
35  180957   99227
36  183958  118434
37  203280  149690
38  214528    1424
39  216882  246776
40  220867   79942
41  222716  145165
42  225232   15957
43  231857   79942
44  233711  236340
45  236340  274301
46  241204   15957
47  246671    1424
48  246776  161936
49  256247   86202
50  259378  175886
51  262902  175886
52  262998  225232
53  274301  236340

#### germany

In [ ]:
area5=area[area['country']=='germany']
area5

         User-ID        ISBN  Book-Rating  country
37861       8971  006080985X            0  germany
37862       8971  0060900075            0  germany
37863       8971  0060901918            0  germany
37864       8971  0061059048            0  germany
37865       8971  0062732765           10  germany
...          ...         ...          ...      ...
1147855   276018  3933191033            0  germany
1147856   276018  3936819009           10  germany
1147857   276018  3980217655            7  germany
1147858   276018  8401380111            0  germany
1147859   276018  9871138148            9  germany

[11708 rows x 4 columns]

In [ ]:
area5['Book-Rating'].unique()

array([ 0, 10,  9,  4,  2,  8,  7,  5,  6,  3,  1], dtype=int64)

In [ ]:
area5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11708 entries, 37861 to 1147859
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      11708 non-null  int64
 1   ISBN         11708 non-null  object
 2   Book-Rating  11708 non-null  int64
 3   country      11708 non-null  object
dtypes: int64(2), object(2)
memory usage: 457.3+ KB

In [ ]:
germany = area5.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
germany.fillna(0,inplace = True)

germany

ISBN,000000000,0003252477,0003300277,0004589777,0006146104,0006165338,0006166598,0006176615,0006374085,0006479898,...,B00005WSAZ,B00007GZZW,B00009EF82,B0000BR9M5,B0000BSH37,B0000C2W66,B0000C7BNG,B0000VZEJQ,B00011SOXI,SELBSTVERLAG
User-ID,,,,,,,,,,,,,,,,,,,,,
8971,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12835,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20859,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28537,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30810,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35718,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39396,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41227,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49422,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54218,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54828,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57449,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71739,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75115,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,8.0,0.0
81128,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84831,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
88283,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0
92405,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97598,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107951,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
132492,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
133567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140826,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141210,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
143909,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144255,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159390,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160032,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160406,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160409,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160410,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160414,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160416,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
163319,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
173679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182086,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
184672,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
189227,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
202173,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
212088,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
214244,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
215225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
222488,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
241198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
243876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250359,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
germany_similarity = 1 - pairwise_distances(germany,metric='cosine')
np.fill_diagonal(germany_similarity,0)

germany_similarity = pd.DataFrame(germany_similarity)
germany_similarity.index = np.sort(area5['User-ID'].unique())
germany_similarity.columns = np.sort(area5['User-ID'].unique())

germany_similarity

,8971,12657,12835,20859,24945,28537,30810,35407,35718,39396,...,202173,212088,214244,215225,222488,241198,243876,250359,264903,276018
8971,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.011813,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
12657,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
12835,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.008477,0.033669,0.000000,0.025064,...,0.000000,0.017293,0.018658,0.000000,0.018638,0.000000,0.000000,0.0,0.000000,0.046213
20859,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
24945,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.027056,0.000000,0.0,0.000000,0.000000
28537,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.040166,0.000000,...,0.021517,0.000000,0.000000,0.000000,0.017949,0.000000,0.000000,0.0,0.025462,0.000000
30810,0.011813,0.0,0.008477,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.018256,0.000000,0.004396,0.000000,0.0,0.000000,0.000000
35407,0.000000,0.0,0.033669,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.016261,...,0.000000,0.010845,0.020060,0.024653,0.054216,0.011971,0.015959,0.0,0.000000,0.046372
35718,0.000000,0.0,0.000000,0.0,0.000000,0.040166,0.000000,0.000000,0.000000,0.021443,...,0.000000,0.000000,0.000000,0.000000,0.043234,0.000000,0.000000,0.0,0.000000,0.000000
39396,0.000000,0.0,0.025064,0.0,0.000000,0.000000,0.000000,0.016261,0.021443,0.000000,...,0.000000,0.021227,0.049078,0.000000,0.012671,0.000000,0.052208,0.0,0.000000,0.030255
41227,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.016207,0.000000,0.000000,...,0.016560,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
49422,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.047232,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
54218,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
54828,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
57449,0.000000,0.0,0.028439,0.0,0.000000,0.041033,0.000000,0.025796,0.000000,0.035974,...,0.000000,0.000000,0.023357,0.000000,0.039262,0.004536,0.019113,0.0,0.000000,0.000000
66483,0.000000,0.0,0.004821,0.0,0.000000,0.000000,0.000000,0.000000,0.024408,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.020194,0.006481,0.000000,0.0,0.000000,0.000000
71739,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.014949,0.000000,0.047964,...,0.000000,0.000000,0.000000,0.000000,0.050156,0.000000,0.025317,0.0,0.000000,0.000000
75115,0.000000,0.0,0.076043,0.0,0.000000,0.000000,0.000000,0.022962,0.000000,0.044079,...,0.024751,0.023346,0.025190,0.013268,0.024470,0.014908,0.009815,0.0,0.000000,0.148628
80945,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
81128,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.049934,0.000000,0.000000,0.005172,0.000000,0.0,0.000000,0.000000
84831,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.010615,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
88283,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.008863,0.000000,0.000000,...,0.000000,0.013222,0.000000,0.000000,0.000000,0.000000,0.018762,0.0,0.000000,0.000000
92405,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.002616,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001661,0.0,0.000000,0.000000
97598,0.000000,0.0,0.069953,0.0,0.000000,0.000000,0.000000,0.021058,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.014181,0.000000,0.000000,0.0,0.000000,0.000000
100644,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.015257,0.000000,0.000000,...,0.035634,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
107951,0.000000,0.0,0.013071,0.0,0.000000,0.000000,0.000000,0.000000,0.010134,0.008825,...,0.000000,0.000000,0.000000,0.000000,0.015970,0.000000,0.000000,0.0,0.000000,0.000000
132492,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.037651,0.000000,0.021551,0.034333,...,0.000000,0.000000,0.023019,0.000000,0.000000,0.015040,0.000188,0.0,0.000000,0.000000
133567,0.000000,0.0,0.020790,0.0,0.000000,0.000000,0.000000,0.036290,0.000000,0.025520,...,0.000000,0.025531,0.027547,0.000000,0.000000,0.000000,0.028982,0.0,0.000000,0.036389
140826,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
140879,0.000000,0.0,0.017243,0.0,0.000000,0.000000,0.010169,0.012359,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.011890,0.005887,0.000000,0.0,0.000000,0.000000
141210,0.000000,0.0,0.010622,0.0,0.000000,0.000000,0.000000,0.025694,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.009531,0.000000,0.012851,0.000000,0.0,0.000000,0.000000
143909,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.049767,0.000000,0.026483,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
144255,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.056855,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
159390,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.022418,0.000000,0.000000,...,0.000000,0.020260,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160032,0.000000,0.0,0.029065,0.0,0.000000,0.011551,0.000000,0.017360,0.000000,0.020387,...,0.000000,0.000000,0.000000,0.000000,0.012025,0.008931,0.000000,0.0,0.034118,0.029070
160406,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160407,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160408,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160409,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160410,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160414,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160415,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160416,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
163319,0.000000,0.0,0.000000,0.0,0.000000,0.006976,0.000000,0.014910,0.000000,0.000000,...,0.000000,0.012512,0.017358,0.000000,0.008299,0.000000,0.000000,0.0,0.020603,0.000000
173679,0.017158,0.0,0.000000,0.0,0.050281,0.011011,0.000000,0.000000,0.000000,0.031309,...,0.027482,0.017497,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
182085,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.001786,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
182086,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
184672,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
189227,0.000000,0.0,0.000000,0.0,0.000000,0.030349,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.044820,0.000000
201548,0.000000,0.0,0.016534,0.0,0.000000,0.023656,0.000000,0.009875,0.000000,0.011598,...,0.000000,0.000000,0.000000,0.000000,0.008978,0.000000,0.000000,0.0,0.000000,0.000000
202173,0.000000,0.0,0.000000,0.0,0.000000,0.021517,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.020822,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.048134
212088,0.000000,0.0,0.017293,0.0,0.000000,0.000000,0.000000,0.010845,0.000000,0.021227,...,0.000000,0.000000,0.022913,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.030268
214244,0.000000,0.0,0.018658,0.0,0.000000,0.000000,0.000000,0.020060,0.000000,0.049078,...,0.020822,0.022913,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.032658
215225,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.018256,0.024653,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.016052,0.000000,0.0,0.000000,0.000000
222488,0.000000,0.0,0.018638,0.0,0.000000,0.017949,0.000000,0.054216,0.043234,0.012671,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.005397,0.030005,0.0,0.000000,0.000000
241198,0.000000,0.0,0.000000,0.0,0.027056,0.000000,0.004396,0.011971,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.016052,0.005397,0.000000,0.000000,0.0,0.000000,0.007952
243876,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.015959,0.000000,0.052208,...,0.000000,0.000000,0.000000,0.000000,0.030005,0.000000,0.000000,0.0,0.000000,0.000000
250359,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
264903,0.000000,0.0,0.000000,0.0,0.000000,0.025462,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
276018,0.000000,0.0,0.046213,0.0,0.000000,0.000000,0.000000,0.046372,0.000000,0.030255,...,0.048134,0.030268,0.032658,0.000000,0.000000,0.007952,0.000000,0.0,0.000000,0.000000

In [ ]:
germany_similarity1 = pd.DataFrame(
    {
        'user-1' : germany_similarity.idxmax().index,
        'user-2' : germany_similarity.idxmax().values
    }
)

germany_similarity1

    user-1  user-2
0     8971  173679
1    12657    8971
2    12835   75115
3    20859    8971
4    24945  173679
5    28537   57449
6    30810  132492
7    35407  222488
8    35718  144255
9    39396  243876
10   41227   71739
11   49422  202173
12   54218  182085
13   54828    8971
14   57449   71739
15   66483   75115
16   71739   57449
17   75115  276018
18   80945  144255
19   81128  214244
20   84831   35407
21   88283  243876
22   92405   80945
23   97598   12835
24  100644  140879
25  107951  143909
26  132492   30810
27  133567  276018
28  140826    8971
29  140879  100644
30  141210   75115
31  143909  202173
32  144255   35718
33  159390  201548
34  160032   75115
35  160406    8971
36  160407    8971
37  160408    8971
38  160409    8971
39  160410    8971
40  160414    8971
41  160415    8971
42  160416    8971
43  163319  264903
44  173679   24945
45  182085  182086
46  182086  182085
47  184672    8971
48  189227  264903
49  201548  159390
50  202173  143909
51  212088  276018
52  214244   81128
53  215225   35407
54  222488   35407
55  241198   24945
56  243876   39396
57  250359    8971
58  264903  189227
59  276018   75115

#### others

In [ ]:
area6=area[(area['country'] != 'usa') & (area['country'] != 'canada') & (area['country'] != 'unitedkingdom') &(area['country'] != 'australia') & (area['country'] != 'germany')]
area6

         User-ID        ISBN  Book-Rating country
412       276925  0006511929            0   spain
413       276925  002542730X           10   spain
414       276925  0060520507            0   spain
415       276925  0060930934            0   spain
416       276925  0060951303            0   spain
...          ...         ...          ...     ...
1149045   276538  3893313672            0     NaN
1149046   276538  3895254428            0     NaN
1149047   276538  3928950495            6     NaN
1149048   276538  3980367606            0     NaN
1149049   276538  3980629007            0     NaN

[73352 rows x 4 columns]

In [ ]:
area6['Book-Rating'].unique()

array([ 0, 10,  7,  6,  5,  8,  9,  4,  3,  2,  1], dtype=int64)

In [ ]:
area6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73352 entries, 412 to 1149049
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      73352 non-null  int64
 1   ISBN         73352 non-null  object
 2   Book-Rating  73352 non-null  int64
 3   country      64378 non-null  object
dtypes: int64(2), object(2)
memory usage: 2.8+ MB

In [ ]:
others = area6.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
others.fillna(0,inplace = True)

others

ISBN,0330299891,0375404120,0586045007,9022906116,9032803328,9044922564,9044922572,9044922718,9044923161,904492401X,...,O805063196,O9088446X,UNGRANDHOMMED,X000000000,Z380703475,ZR903CX0003,"\0432534220\""""","\2842053052\""""","\8887517452\""""","\8888809228\"""""
User-ID,,,,,,,,,,,,,,,,,,,,,
183,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2442,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
275414,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,5.0
276538,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277478,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
others_similarity = 1 - pairwise_distances(others,metric='cosine')
np.fill_diagonal(others_similarity,0)

others_similarity = pd.DataFrame(others_similarity)
others_similarity.index = np.sort(area6['User-ID'].unique())
others_similarity.columns = np.sort(area6['User-ID'].unique())

others_similarity

,183,1903,2442,3757,5903,6703,8890,11120,11676,12982,...,272482,272715,273110,273190,274004,274111,275414,276538,276925,277478
183,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004574,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2442,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001524,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003258,0.002305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.011847,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001756,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
275414,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000047,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276538,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000734,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.011152,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277478,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006771,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
others_similarity1 = pd.DataFrame(
    {
        'user-1' : others_similarity.idxmax().index,
        'user-2' : others_similarity.idxmax().values
    }
)

others_similarity1

     user-1  user-2
0       183  261379
1      1903   38281
2      2442   26813
3      3757  131126
4      5903   27788
..      ...     ...
260  274111   70999
261  275414   29117
262  276538   11676
263  276925   81207
264  277478  199092

[265 rows x 2 columns]

### Preparing Model Based On Area

#### usa

In [ ]:
area1=area[area['country']=='usa']
area1

         User-ID        ISBN  Book-Rating country
1456      277427  002542730X           10     usa
1457      277427  0026217457            0     usa
1458      277427  003008685X            8     usa
1459      277427  0030615321            0     usa
1460      277427  0060002050            0     usa
...          ...         ...          ...     ...
1149633   276680  1884910033            0     usa
1149634   276680  1888173408            7     usa
1149635   276680  1888173564            8     usa
1149636   276680  1888173572            0     usa
1149637   276680  1931561648            9     usa

[474698 rows x 4 columns]

In [ ]:
area1['Book-Rating'].unique()

array([10,  0,  8,  7,  9,  6,  5,  4,  2,  3,  1], dtype=int64)

In [ ]:
area1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 474698 entries, 1456 to 1149637
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   User-ID      474698 non-null  int64
 1   ISBN         474698 non-null  object
 2   Book-Rating  474698 non-null  int64
 3   country      474698 non-null  object
dtypes: int64(2), object(2)
memory usage: 18.1+ MB

In [ ]:
usa = area1.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
usa.fillna(0,inplace = True)

usa

ISBN,0375404120,*0515128325,0000000051,0000001042283,0000018030,0001047868,0001048759,0001052276,0001053736,0001053744,...,SBN67001026X,T110105305048,T110105705048,TBR0385495641,THEALLTRUETRA,THECATASTROPH,THEFLYINGACE,"YOUTELLEM,AND",b00005wz75,Ô½crosoft
User-ID,,,,,,,,,,,,,,,,,,,,,
254,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
507,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1435,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1733,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278188,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278418,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
usa_similarity = 1 - pairwise_distances(usa,metric='cosine')
np.fill_diagonal(usa_similarity,0)

usa_similarity = pd.DataFrame(usa_similarity)
usa_similarity.index = np.sort(area1['User-ID'].unique())
usa_similarity.columns = np.sort(area1['User-ID'].unique())

usa_similarity

,254,507,882,1435,1733,2033,2110,2276,2358,2766,...,274808,275020,275970,276463,276680,277427,277639,278137,278188,278418
254,0.000000,0.030295,0.023211,0.000000,0.000000,0.052825,0.000000,0.000000,0.0,0.000000,...,0.00000,0.0,0.012727,0.025349,0.016365,0.000000,0.0,0.0,0.0,0.0
507,0.030295,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.032066,0.0,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
882,0.023211,0.000000,0.000000,0.000000,0.010862,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.0,0.000000,0.000000,0.040752,0.020002,0.0,0.0,0.0,0.0
1435,0.000000,0.000000,0.000000,0.000000,0.001383,0.000000,0.000000,0.000000,0.0,0.007951,...,0.05544,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
1733,0.000000,0.000000,0.010862,0.001383,0.000000,0.000000,0.016085,0.000000,0.0,0.001095,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,0.000000,0.000000,0.020002,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.020162,...,0.00000,0.0,0.006398,0.000000,0.029510,0.000000,0.0,0.0,0.0,0.0
277639,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.023342,0.0,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
278137,0.000000,0.000000,0.000000,0.000000,0.000000,0.005546,0.000000,0.000000,0.0,0.000000,...,0.00000,0.0,0.012370,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
278188,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
278418,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.006667,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0

In [ ]:
usa_similarity1 = pd.DataFrame(
    {
        'user-1' : usa_similarity.idxmax().index,
        'user-2' : usa_similarity.idxmax().values
    }
)

usa_similarity1

      user-1  user-2
0        254   88122
1        507   37712
2        882  149084
3       1435  264543
4       1733  180917
...      ...     ...
1187  277427  224340
1188  277639  240035
1189  278137   31040
1190  278188  218569
1191  278418  170742

[1192 rows x 2 columns]

#### canada

In [ ]:
area2=area[area['country']=='canada']
area2

         User-ID        ISBN  Book-Rating country
25448       6242  0002244098            5  canada
25449       6242  0006385370            7  canada
25450       6242  0006391761            6  canada
25451       6242  0006392237            7  canada
25452       6242  0006480608            7  canada
...          ...         ...          ...     ...
1128315   270713  1895897645            0  canada
1128316   270713  1896239684            0  canada
1128317   270713  1930051220            0  canada
1128318   270713  1931412065            0  canada
1128319   270713  O67174142X            8  canada

[59333 rows x 4 columns]

In [ ]:
area2['Book-Rating'].unique()

array([ 5,  7,  6,  0,  8,  3,  4, 10,  9,  1,  2], dtype=int64)

In [ ]:
area2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59333 entries, 25448 to 1128319
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      59333 non-null  int64
 1   ISBN         59333 non-null  object
 2   Book-Rating  59333 non-null  int64
 3   country      59333 non-null  object
dtypes: int64(2), object(2)
memory usage: 2.3+ MB

In [ ]:
canada = area2.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
canada.fillna(0,inplace = True)

canada

ISBN,0000913154,000104799X,0001055607,0001251782,0001382381,0001382608,0001840517,0001961721,0002000288,0002000474,...,JaneDentinger,LATITUDESOFME,N006485332,O590477412,O67174142X,O774037474,O77O428452,O880015152,O889950962,Q380708353
User-ID,,,,,,,,,,,,,,,,,,,,,
6242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8782,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9417,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16721,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
268300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
268932,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
270554,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
270713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
canada_similarity = 1 - pairwise_distances(canada,metric='cosine')
np.fill_diagonal(canada_similarity,0)

canada_similarity = pd.DataFrame(canada_similarity)
canada_similarity.index = np.sort(area2['User-ID'].unique())
canada_similarity.columns = np.sort(area2['User-ID'].unique())

canada_similarity

,6242,8782,9417,14456,16721,16966,21404,23288,26583,27617,...,260183,263325,263877,264321,265889,266522,268300,268932,270554,270713
6242,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.014166,0.000000,0.008635,0.000000,...,0.006700,0.076761,0.009412,0.013856,0.016795,0.0,0.000000,0.018002,0.086139,0.049439
8782,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.021957,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.013587
9417,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.027912,0.000000,0.000000,0.000000,...,0.000000,0.022453,0.016690,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.011433
14456,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.023019,0.000000,0.000000,0.000000,0.000000,0.0,0.033215,0.012193,0.000000,0.007928
16721,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266522,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.021489,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
268300,0.000000,0.000000,0.000000,0.033215,0.0,0.008803,0.000000,0.000000,0.000000,0.012788,...,0.008216,0.012420,0.000000,0.016127,0.000000,0.0,0.000000,0.000000,0.000000,0.004304
268932,0.018002,0.000000,0.000000,0.012193,0.0,0.000000,0.000000,0.011119,0.000000,0.000000,...,0.000000,0.012260,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.014537,0.010242
270554,0.086139,0.000000,0.000000,0.000000,0.0,0.000000,0.039234,0.000000,0.000000,0.017476,...,0.018946,0.117486,0.021028,0.046437,0.019087,0.0,0.000000,0.014537,0.000000,0.040962
270713,0.049439,0.013587,0.011433,0.007928,0.0,0.000000,0.007433,0.000000,0.000000,0.009120,...,0.012695,0.035431,0.008642,0.027767,0.002792,0.0,0.004304,0.010242,0.040962,0.000000

In [ ]:
canada_similarity1 = pd.DataFrame(
    {
        'user-1' : canada_similarity.idxmax().index,
        'user-2' : canada_similarity.idxmax().values
    }
)

usa_similarity1

      user-1  user-2
0        254   88122
1        507   37712
2        882  149084
3       1435  264543
4       1733  180917
...      ...     ...
1187  277427  224340
1188  277639  240035
1189  278137   31040
1190  278188  218569
1191  278418  170742

[1192 rows x 2 columns]

#### united kingdom

In [ ]:
area3=area[area['country']=='unitedkingdom']
area3

         User-ID        ISBN  Book-Rating        country
29970       7105  0006176917            0  unitedkingdom
29971       7105  0006372570            5  unitedkingdom
29972       7105  0006374093            0  unitedkingdom
29973       7105  0006482880            0  unitedkingdom
29974       7105  0006548717            3  unitedkingdom
...          ...         ...          ...            ...
1137218   273718  1869928318           10  unitedkingdom
1137219   273718  1871592232           10  unitedkingdom
1137220   273718  189830713X           10  unitedkingdom
1137221   273718  1904492355            0  unitedkingdom
1137222   273718  3822862142            9  unitedkingdom

[26139 rows x 4 columns]

In [ ]:
area3['Book-Rating'].unique()

array([ 0,  5,  3,  6,  9,  7, 10,  8,  4,  1,  2], dtype=int64)

In [ ]:
area3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26139 entries, 29970 to 1137222
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      26139 non-null  int64
 1   ISBN         26139 non-null  object
 2   Book-Rating  26139 non-null  int64
 3   country      26139 non-null  object
dtypes: int64(2), object(2)
memory usage: 1021.1+ KB

In [ ]:
unitedkingdom = area3.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
unitedkingdom.fillna(0,inplace = True)

unitedkingdom

ISBN,0*708880258,0000000026307,0000000029841,0000000030670,0000000033220,0000000124911,0000001056518,0001010565,0001046438,000104687X,...,CN109567,CN110912,CN115072,CN124650,CN9944/1142,L583225846,O856856428,O861366301,cn108465,cn113107
User-ID,,,,,,,,,,,,,,,,,,,,,
7105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25533,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30509,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266866,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
269728,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
272225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
273718,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
unitedkingdom_similarity = 1 - pairwise_distances(unitedkingdom,metric='cosine')
np.fill_diagonal(unitedkingdom_similarity,0)

unitedkingdom_similarity = pd.DataFrame(unitedkingdom_similarity)
unitedkingdom_similarity.index = np.sort(area3['User-ID'].unique())
unitedkingdom_similarity.columns = np.sort(area3['User-ID'].unique())

unitedkingdom_similarity

,7105,23902,25533,30509,30712,33888,37567,40647,44925,56271,...,238864,244277,246156,246617,252827,261037,266866,269728,272225,273718
7105,0.000000,0.000000,0.000000,0.0,0.017018,0.036755,0.000000,0.000000,0.00000,0.011463,...,0.052992,0.021861,0.000000,0.011626,0.022752,0.000000,0.000000,0.010238,0.0,0.022771
23902,0.000000,0.000000,0.010436,0.0,0.008272,0.005360,0.003555,0.000000,0.00000,0.005474,...,0.014342,0.000577,0.006422,0.003992,0.002524,0.014567,0.001374,0.001352,0.0,0.011836
25533,0.000000,0.010436,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.021522,...,0.032618,0.000000,0.000000,0.024697,0.000000,0.021310,0.000000,0.016659,0.0,0.000000
30509,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
30712,0.017018,0.008272,0.000000,0.0,0.000000,0.011112,0.014739,0.034013,0.02755,0.000000,...,0.000000,0.000000,0.000000,0.022918,0.010853,0.011884,0.000000,0.009966,0.0,0.012414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261037,0.000000,0.014567,0.021310,0.0,0.011884,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.026079,0.000000,0.000000,0.000000,0.0,0.000000
266866,0.000000,0.001374,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.040633,...,0.032900,0.000000,0.000000,0.000000,0.008779,0.000000,0.000000,0.025958,0.0,0.000000
269728,0.010238,0.001352,0.016659,0.0,0.009966,0.000000,0.000000,0.000000,0.00000,0.006484,...,0.045313,0.000000,0.016950,0.012860,0.000000,0.000000,0.025958,0.000000,0.0,0.000000
272225,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.014338,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
273718,0.022771,0.011836,0.000000,0.0,0.012414,0.016521,0.000000,0.000000,0.00000,0.013668,...,0.026136,0.031007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [ ]:
unitedkingdom_similarity1 = pd.DataFrame(
    {
        'user-1' : unitedkingdom_similarity.idxmax().index,
        'user-2' : unitedkingdom_similarity.idxmax().values
    }
)

unitedkingdom_similarity1

    user-1  user-2
0     7105  238864
1    23902  209516
2    25533   92853
3    30509    7105
4    30712  124688
..     ...     ...
81  261037   60797
82  266866   72451
83  269728  238864
84  272225  100088
85  273718  114446

[86 rows x 2 columns]

#### australia

In [ ]:
area4=area[area['country']=='australia']
area4

         User-ID        ISBN  Book-Rating    country
12725       1424  0007119860            0  australia
12726       1424  0060000805            7  australia
12727       1424  0060505273            0  australia
12728       1424  0060512822            7  australia
12729       1424  0060730552            9  australia
...          ...         ...          ...        ...
1140652   274301  1879237806           10  australia
1140653   274301  1886913439            0  australia
1140654   274301  9994770934           10  australia
1140655   274301  9998914140           10  australia
1140656   274301  B00009NDAN           10  australia

[13575 rows x 4 columns]

In [ ]:
area4['Book-Rating'].unique()

array([ 0,  7,  9,  8,  5,  6, 10,  4,  3,  1,  2], dtype=int64)

In [ ]:
area4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13575 entries, 12725 to 1140656
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      13575 non-null  int64
 1   ISBN         13575 non-null  object
 2   Book-Rating  13575 non-null  int64
 3   country      13575 non-null  object
dtypes: int64(2), object(2)
memory usage: 530.3+ KB

In [ ]:
australia = area4.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
australia.fillna(0,inplace = True)

australia

ISBN,0 00 614494 2,0 85550 000 x,0000000000000,0000001481,0001033085,0001047663,0001048082,0001049879,0001604163,0001604465,...,B0000523SS,B000055Z5S,B00005N5J6,B00005WAEO,B00005X0HL,B0000646QD,B00008NRHQ,B00009NDAN,B0002JV9PY,B0002K6K8O
User-ID,,,,,,,,,,,,,,,,,,,,,
1424,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98787,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99227,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109901,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109955,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112541,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
113817,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
114865,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118434,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121726,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141819,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149690,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
155916,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161936,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168387,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
172248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
175886,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
176062,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
179791,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
180707,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
180957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
183958,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
203280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
214528,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
216882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
220867,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
222716,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225232,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
231857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
233711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
236340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0
241204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
246671,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
246776,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
256247,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
259378,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
262902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
262998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
274301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0

In [ ]:
australia_similarity = 1 - pairwise_distances(australia,metric='cosine')
np.fill_diagonal(australia_similarity,0)

australia_similarity = pd.DataFrame(australia_similarity)
australia_similarity.index = np.sort(area4['User-ID'].unique())
australia_similarity.columns = np.sort(area4['User-ID'].unique())

australia_similarity

,1424,13995,15957,16161,16943,30711,42400,44296,53729,79942,...,233711,236340,241204,246671,246776,256247,259378,262902,262998,274301
1424,0.000000,0.015391,0.027016,0.017772,0.000000,0.011629,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.045859,0.000000,0.025029,0.030255,0.006322,0.000000
13995,0.015391,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.024298,0.000000,...,0.000000,0.000000,0.014216,0.0,0.000000,0.000000,0.027720,0.000000,0.010287,0.000000
15957,0.027016,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.024490,0.000000,...,0.035814,0.000000,0.065972,0.0,0.000000,0.078517,0.000000,0.000000,0.010157,0.037237
16161,0.017772,0.000000,0.000000,0.000000,0.000000,0.011154,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.023458,0.000000,0.000000,0.015873,0.009913,0.000000
16943,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.027149,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30711,0.011629,0.000000,0.000000,0.011154,0.000000,0.000000,0.0,0.017003,0.000000,0.000000,...,0.021316,0.004222,0.000000,0.0,0.032405,0.014787,0.000000,0.025196,0.003967,0.007382
42400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44296,0.000000,0.000000,0.000000,0.000000,0.000000,0.017003,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.010701
53729,0.000000,0.024298,0.024490,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.012544,0.018618,0.0,0.000000,0.000000,0.048620,0.021700,0.000000,0.000000
79942,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.023211,0.000000,0.000000,0.0,0.000000,0.022617,0.000000,0.000000,0.009875,0.000000
86033,0.000000,0.000000,0.000000,0.000000,0.000000,0.018704,0.0,0.000000,0.000000,0.000000,...,0.013752,0.000000,0.000000,0.0,0.000000,0.018216,0.000000,0.000000,0.000000,0.000000
86202,0.000000,0.000000,0.057699,0.000000,0.000000,0.083013,0.0,0.000000,0.020361,0.000000,...,0.018012,0.012684,0.031466,0.0,0.000000,0.099038,0.026547,0.034480,0.013866,0.019010
98787,0.016035,0.000000,0.000000,0.021971,0.000000,0.040255,0.0,0.000000,0.000000,0.000000,...,0.031492,0.022786,0.017774,0.0,0.000000,0.000000,0.049509,0.020716,0.000000,0.020357
99227,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.033519,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
109901,0.045382,0.000000,0.020249,0.000000,0.022204,0.000000,0.0,0.012635,0.012393,0.016149,...,0.000000,0.015220,0.000000,0.0,0.000000,0.000000,0.016415,0.024803,0.002073,0.039534
109955,0.000000,0.000000,0.000000,0.000000,0.000000,0.008003,0.0,0.014732,0.000000,0.000000,...,0.000000,0.017488,0.000000,0.0,0.020780,0.000000,0.000000,0.000000,0.000000,0.000000
112541,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.010011,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
113817,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.029767,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
114865,0.000000,0.000000,0.000000,0.000000,0.018422,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.003660,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
118434,0.030151,0.000000,0.000000,0.028918,0.000000,0.031538,0.0,0.000000,0.000000,0.000000,...,0.016119,0.000000,0.000000,0.0,0.039798,0.000000,0.000000,0.000000,0.010286,0.000000
121726,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.025067,0.000000,0.000000,0.000000,0.000000
123625,0.000000,0.000000,0.000000,0.000000,0.000000,0.010262,0.0,0.000000,0.000000,0.000000,...,0.025913,0.011080,0.000000,0.0,0.000000,0.000000,0.000000,0.019168,0.000000,0.000000
141819,0.000000,0.000000,0.000000,0.000000,0.000000,0.012748,0.0,0.010266,0.000000,0.000000,...,0.014479,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
144131,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
145165,0.000000,0.000000,0.000000,0.000000,0.000000,0.029448,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.035494,0.025460,0.000000,0.000000
149690,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.032094,0.000000,...,0.007887,0.013995,0.000000,0.0,0.036347,0.000000,0.032546,0.035018,0.000000,0.000000
155916,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
157655,0.043591,0.000000,0.043855,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.038456,0.000000,0.0,0.000000,0.000000,0.031107,0.000000,0.010262,0.000000
161936,0.035796,0.000000,0.000000,0.018311,0.000000,0.035778,0.0,0.000000,0.000000,0.000000,...,0.017011,0.006160,0.000000,0.0,0.072798,0.023975,0.029011,0.019183,0.006513,0.000000
168387,0.000000,0.000000,0.047065,0.000000,0.000000,0.000000,0.0,0.025379,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
172248,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
175886,0.000000,0.000000,0.000000,0.000000,0.000000,0.050991,0.0,0.000000,0.000000,0.000000,...,0.041804,0.000000,0.000000,0.0,0.000000,0.000000,0.060650,0.108134,0.000000,0.000000
176062,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.041865,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
179791,0.000000,0.000000,0.000000,0.000000,0.000000,0.015020,0.0,0.000000,0.031047,0.000000,...,0.000000,0.008703,0.000000,0.0,0.017581,0.000000,0.000000,0.000000,0.000000,0.009511
180707,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
180957,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.016369,0.010512,0.000000,0.000000,0.000000,0.000000
183958,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.009245,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.011263,0.000000,0.000000
203280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.026746,0.000000,...,0.000000,0.031656,0.000000,0.0,0.000000,0.000000,0.000000,0.029183,0.000000,0.034595
214528,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
216882,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.025783,...,0.000000,0.000000,0.000000,0.0,0.032014,0.000000,0.000000,0.000000,0.000000,0.000000
220867,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.080790,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.015809,0.000000
222716,0.000000,0.000000,0.000000,0.000000,0.065079,0.014903,0.0,0.000000,0.000000,0.000000,...,0.028564,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.035790,0.000000,0.000000
225232,0.000000,0.000000,0.045961,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.006292,0.000000,0.000000,0.0,0.011651,0.011085,0.009273,0.000000,0.017303,0.004980
231857,0.009422,0.000000,0.000000,0.000000,0.000000,0.014642,0.0,0.000000,0.016734,0.046606,...,0.000000,0.005212,0.000000,0.0,0.000000,0.020284,0.014848,0.000000,0.000000,0.025632
233711,0.000000,0.000000,0.035814,0.000000,0.027149,0.021316,0.0,0.000000,0.000000,0.023211,...,0.000000,0.052864,0.000000,0.0,0.000000,0.021593,0.000000,0.012798,0.005587,0.000000
236340,0.000000,0.000000,0.000000,0.000000,0.000000,0.004222,0.0,0.000000,0.012544,0.000000,...,0.052864,0.000000,0.000000,0.0,0.014206,0.000000,0.014538,0.000000,0.004196,0.140903
241204,0.000000,0.014216,0.065972,0.000000,0.000000,0.000000,0.0,0.000000,0.018618,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
246671,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
246776,0.045859,0.000000,0.000000,0.023458,0.000000,0.032405,0.0,0.000000,0.000000,0.000000,...,0.000000,0.014206,0.000000,0.0,0.000000,0.040953,0.000000,0.024576,0.008344,0.000000
256247,0.000000,0.000000,0.078517,0.000000,0.000000,0.014787,0.0,0.000000,0.000000,0.022617,...,0.021593,0.000000,0.000000,0.0,0.040953,0.000000,0.000000,0.000000,0.006124,0.000000
259378,0.025029,0.027720,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.048620,0.000000,...,0.000000,0.014538,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
262902,0.030255,0.000000,0.000000,0.015873,0.000000,0.025196,0.0,0.000000,0.021700,0.000000,...,0.012798,0.000000,0.000000,0.0,0.024576,0.000000,0.000000,0.000000,0.000000,0.007239
262998,0.006322,0.010287,0.010157,0.009913,0.000000,0.003967,0.0,0.000000,0.000000,0.009875,...,0.005587,0.004196,0.000000,0.0,0.008344,0.006124,0.000000,0.000000,0.000000,0.002866
274301,0.000000,0.000000,0.037237,0.000000,0.000000,0.007382,0.0,0.010701,0.000000,0.000000,...,0.000000,0.140903,0.000000,0.0,0.000000,0.000000,0.000000,0.007239,0.002866,0.000000

In [ ]:
australia_similarity1 = pd.DataFrame(
    {
        'user-1' : australia_similarity.idxmax().index,
        'user-2' : australia_similarity.idxmax().values
    }
)

australia_similarity1

    user-1  user-2
0     1424  246776
1    13995  259378
2    15957  256247
3    16161  118434
4    16943  222716
5    30711   86202
6    42400    1424
7    44296  168387
8    53729  259378
9    79942  220867
10   86033  145165
11   86202   98787
12   98787   86202
13   99227  220867
14  109901    1424
15  109955  246776
16  112541  149690
17  113817   86202
18  114865   16943
19  118434  161936
20  121726  256247
21  123625  149690
22  141819  233711
23  144131    1424
24  145165  222716
25  149690  123625
26  155916    1424
27  157655   15957
28  161936  246776
29  168387  176062
30  172248    1424
31  175886  262902
32  176062  168387
33  179791   53729
34  180707    1424
35  180957   99227
36  183958  118434
37  203280  149690
38  214528    1424
39  216882  246776
40  220867   79942
41  222716  145165
42  225232   15957
43  231857   79942
44  233711  236340
45  236340  274301
46  241204   15957
47  246671    1424
48  246776  161936
49  256247   86202
50  259378  175886
51  262902  175886
52  262998  225232
53  274301  236340

#### germany

In [ ]:
area5=area[area['country']=='germany']
area5

         User-ID        ISBN  Book-Rating  country
37861       8971  006080985X            0  germany
37862       8971  0060900075            0  germany
37863       8971  0060901918            0  germany
37864       8971  0061059048            0  germany
37865       8971  0062732765           10  germany
...          ...         ...          ...      ...
1147855   276018  3933191033            0  germany
1147856   276018  3936819009           10  germany
1147857   276018  3980217655            7  germany
1147858   276018  8401380111            0  germany
1147859   276018  9871138148            9  germany

[11708 rows x 4 columns]

In [ ]:
area5['Book-Rating'].unique()

array([ 0, 10,  9,  4,  2,  8,  7,  5,  6,  3,  1], dtype=int64)

In [ ]:
area5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11708 entries, 37861 to 1147859
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      11708 non-null  int64
 1   ISBN         11708 non-null  object
 2   Book-Rating  11708 non-null  int64
 3   country      11708 non-null  object
dtypes: int64(2), object(2)
memory usage: 457.3+ KB

In [ ]:
germany = area5.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
germany.fillna(0,inplace = True)

germany

ISBN,000000000,0003252477,0003300277,0004589777,0006146104,0006165338,0006166598,0006176615,0006374085,0006479898,...,B00005WSAZ,B00007GZZW,B00009EF82,B0000BR9M5,B0000BSH37,B0000C2W66,B0000C7BNG,B0000VZEJQ,B00011SOXI,SELBSTVERLAG
User-ID,,,,,,,,,,,,,,,,,,,,,
8971,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12835,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20859,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28537,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30810,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35718,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39396,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41227,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49422,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54218,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54828,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57449,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71739,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75115,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,8.0,0.0
81128,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84831,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
88283,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0
92405,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97598,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107951,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
132492,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
133567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140826,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141210,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
143909,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144255,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159390,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160032,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160406,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160409,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160410,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160414,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160416,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
163319,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
173679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182086,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
184672,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
189227,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
202173,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
212088,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
214244,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
215225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
222488,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
241198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
243876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250359,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
germany_similarity = 1 - pairwise_distances(germany,metric='cosine')
np.fill_diagonal(germany_similarity,0)

germany_similarity = pd.DataFrame(germany_similarity)
germany_similarity.index = np.sort(area5['User-ID'].unique())
germany_similarity.columns = np.sort(area5['User-ID'].unique())

germany_similarity

,8971,12657,12835,20859,24945,28537,30810,35407,35718,39396,...,202173,212088,214244,215225,222488,241198,243876,250359,264903,276018
8971,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.011813,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
12657,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
12835,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.008477,0.033669,0.000000,0.025064,...,0.000000,0.017293,0.018658,0.000000,0.018638,0.000000,0.000000,0.0,0.000000,0.046213
20859,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
24945,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.027056,0.000000,0.0,0.000000,0.000000
28537,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.040166,0.000000,...,0.021517,0.000000,0.000000,0.000000,0.017949,0.000000,0.000000,0.0,0.025462,0.000000
30810,0.011813,0.0,0.008477,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.018256,0.000000,0.004396,0.000000,0.0,0.000000,0.000000
35407,0.000000,0.0,0.033669,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.016261,...,0.000000,0.010845,0.020060,0.024653,0.054216,0.011971,0.015959,0.0,0.000000,0.046372
35718,0.000000,0.0,0.000000,0.0,0.000000,0.040166,0.000000,0.000000,0.000000,0.021443,...,0.000000,0.000000,0.000000,0.000000,0.043234,0.000000,0.000000,0.0,0.000000,0.000000
39396,0.000000,0.0,0.025064,0.0,0.000000,0.000000,0.000000,0.016261,0.021443,0.000000,...,0.000000,0.021227,0.049078,0.000000,0.012671,0.000000,0.052208,0.0,0.000000,0.030255
41227,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.016207,0.000000,0.000000,...,0.016560,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
49422,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.047232,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
54218,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
54828,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
57449,0.000000,0.0,0.028439,0.0,0.000000,0.041033,0.000000,0.025796,0.000000,0.035974,...,0.000000,0.000000,0.023357,0.000000,0.039262,0.004536,0.019113,0.0,0.000000,0.000000
66483,0.000000,0.0,0.004821,0.0,0.000000,0.000000,0.000000,0.000000,0.024408,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.020194,0.006481,0.000000,0.0,0.000000,0.000000
71739,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.014949,0.000000,0.047964,...,0.000000,0.000000,0.000000,0.000000,0.050156,0.000000,0.025317,0.0,0.000000,0.000000
75115,0.000000,0.0,0.076043,0.0,0.000000,0.000000,0.000000,0.022962,0.000000,0.044079,...,0.024751,0.023346,0.025190,0.013268,0.024470,0.014908,0.009815,0.0,0.000000,0.148628
80945,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
81128,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.049934,0.000000,0.000000,0.005172,0.000000,0.0,0.000000,0.000000
84831,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.010615,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
88283,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.008863,0.000000,0.000000,...,0.000000,0.013222,0.000000,0.000000,0.000000,0.000000,0.018762,0.0,0.000000,0.000000
92405,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.002616,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001661,0.0,0.000000,0.000000
97598,0.000000,0.0,0.069953,0.0,0.000000,0.000000,0.000000,0.021058,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.014181,0.000000,0.000000,0.0,0.000000,0.000000
100644,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.015257,0.000000,0.000000,...,0.035634,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
107951,0.000000,0.0,0.013071,0.0,0.000000,0.000000,0.000000,0.000000,0.010134,0.008825,...,0.000000,0.000000,0.000000,0.000000,0.015970,0.000000,0.000000,0.0,0.000000,0.000000
132492,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.037651,0.000000,0.021551,0.034333,...,0.000000,0.000000,0.023019,0.000000,0.000000,0.015040,0.000188,0.0,0.000000,0.000000
133567,0.000000,0.0,0.020790,0.0,0.000000,0.000000,0.000000,0.036290,0.000000,0.025520,...,0.000000,0.025531,0.027547,0.000000,0.000000,0.000000,0.028982,0.0,0.000000,0.036389
140826,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
140879,0.000000,0.0,0.017243,0.0,0.000000,0.000000,0.010169,0.012359,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.011890,0.005887,0.000000,0.0,0.000000,0.000000
141210,0.000000,0.0,0.010622,0.0,0.000000,0.000000,0.000000,0.025694,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.009531,0.000000,0.012851,0.000000,0.0,0.000000,0.000000
143909,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.049767,0.000000,0.026483,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
144255,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.056855,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
159390,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.022418,0.000000,0.000000,...,0.000000,0.020260,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160032,0.000000,0.0,0.029065,0.0,0.000000,0.011551,0.000000,0.017360,0.000000,0.020387,...,0.000000,0.000000,0.000000,0.000000,0.012025,0.008931,0.000000,0.0,0.034118,0.029070
160406,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160407,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160408,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160409,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160410,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160414,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160415,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
160416,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
163319,0.000000,0.0,0.000000,0.0,0.000000,0.006976,0.000000,0.014910,0.000000,0.000000,...,0.000000,0.012512,0.017358,0.000000,0.008299,0.000000,0.000000,0.0,0.020603,0.000000
173679,0.017158,0.0,0.000000,0.0,0.050281,0.011011,0.000000,0.000000,0.000000,0.031309,...,0.027482,0.017497,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
182085,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.001786,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
182086,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
184672,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
189227,0.000000,0.0,0.000000,0.0,0.000000,0.030349,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.044820,0.000000
201548,0.000000,0.0,0.016534,0.0,0.000000,0.023656,0.000000,0.009875,0.000000,0.011598,...,0.000000,0.000000,0.000000,0.000000,0.008978,0.000000,0.000000,0.0,0.000000,0.000000
202173,0.000000,0.0,0.000000,0.0,0.000000,0.021517,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.020822,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.048134
212088,0.000000,0.0,0.017293,0.0,0.000000,0.000000,0.000000,0.010845,0.000000,0.021227,...,0.000000,0.000000,0.022913,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.030268
214244,0.000000,0.0,0.018658,0.0,0.000000,0.000000,0.000000,0.020060,0.000000,0.049078,...,0.020822,0.022913,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.032658
215225,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.018256,0.024653,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.016052,0.000000,0.0,0.000000,0.000000
222488,0.000000,0.0,0.018638,0.0,0.000000,0.017949,0.000000,0.054216,0.043234,0.012671,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.005397,0.030005,0.0,0.000000,0.000000
241198,0.000000,0.0,0.000000,0.0,0.027056,0.000000,0.004396,0.011971,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.016052,0.005397,0.000000,0.000000,0.0,0.000000,0.007952
243876,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.015959,0.000000,0.052208,...,0.000000,0.000000,0.000000,0.000000,0.030005,0.000000,0.000000,0.0,0.000000,0.000000
250359,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
264903,0.000000,0.0,0.000000,0.0,0.000000,0.025462,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
276018,0.000000,0.0,0.046213,0.0,0.000000,0.000000,0.000000,0.046372,0.000000,0.030255,...,0.048134,0.030268,0.032658,0.000000,0.000000,0.007952,0.000000,0.0,0.000000,0.000000

In [ ]:
germany_similarity1 = pd.DataFrame(
    {
        'user-1' : germany_similarity.idxmax().index,
        'user-2' : germany_similarity.idxmax().values
    }
)

germany_similarity1

    user-1  user-2
0     8971  173679
1    12657    8971
2    12835   75115
3    20859    8971
4    24945  173679
5    28537   57449
6    30810  132492
7    35407  222488
8    35718  144255
9    39396  243876
10   41227   71739
11   49422  202173
12   54218  182085
13   54828    8971
14   57449   71739
15   66483   75115
16   71739   57449
17   75115  276018
18   80945  144255
19   81128  214244
20   84831   35407
21   88283  243876
22   92405   80945
23   97598   12835
24  100644  140879
25  107951  143909
26  132492   30810
27  133567  276018
28  140826    8971
29  140879  100644
30  141210   75115
31  143909  202173
32  144255   35718
33  159390  201548
34  160032   75115
35  160406    8971
36  160407    8971
37  160408    8971
38  160409    8971
39  160410    8971
40  160414    8971
41  160415    8971
42  160416    8971
43  163319  264903
44  173679   24945
45  182085  182086
46  182086  182085
47  184672    8971
48  189227  264903
49  201548  159390
50  202173  143909
51  212088  276018
52  214244   81128
53  215225   35407
54  222488   35407
55  241198   24945
56  243876   39396
57  250359    8971
58  264903  189227
59  276018   75115

#### others

In [ ]:
area6=area[(area['country'] != 'usa') & (area['country'] != 'canada') & (area['country'] != 'unitedkingdom') &(area['country'] != 'australia') & (area['country'] != 'germany')]
area6

         User-ID        ISBN  Book-Rating country
412       276925  0006511929            0   spain
413       276925  002542730X           10   spain
414       276925  0060520507            0   spain
415       276925  0060930934            0   spain
416       276925  0060951303            0   spain
...          ...         ...          ...     ...
1149045   276538  3893313672            0     NaN
1149046   276538  3895254428            0     NaN
1149047   276538  3928950495            6     NaN
1149048   276538  3980367606            0     NaN
1149049   276538  3980629007            0     NaN

[73352 rows x 4 columns]

In [ ]:
area6['Book-Rating'].unique()

array([ 0, 10,  7,  6,  5,  8,  9,  4,  3,  2,  1], dtype=int64)

In [ ]:
area6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73352 entries, 412 to 1149049
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      73352 non-null  int64
 1   ISBN         73352 non-null  object
 2   Book-Rating  73352 non-null  int64
 3   country      64378 non-null  object
dtypes: int64(2), object(2)
memory usage: 2.8+ MB

In [ ]:
others = area6.pivot_table(values='Book-Rating', index='User-ID',columns='ISBN')
others.fillna(0,inplace = True)

others

ISBN,0330299891,0375404120,0586045007,9022906116,9032803328,9044922564,9044922572,9044922718,9044923161,904492401X,...,O805063196,O9088446X,UNGRANDHOMMED,X000000000,Z380703475,ZR903CX0003,"\0432534220\""""","\2842053052\""""","\8887517452\""""","\8888809228\"""""
User-ID,,,,,,,,,,,,,,,,,,,,,
183,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2442,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
275414,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,5.0
276538,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277478,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
others_similarity = 1 - pairwise_distances(others,metric='cosine')
np.fill_diagonal(others_similarity,0)

others_similarity = pd.DataFrame(others_similarity)
others_similarity.index = np.sort(area6['User-ID'].unique())
others_similarity.columns = np.sort(area6['User-ID'].unique())

others_similarity

,183,1903,2442,3757,5903,6703,8890,11120,11676,12982,...,272482,272715,273110,273190,274004,274111,275414,276538,276925,277478
183,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004574,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2442,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001524,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003258,0.002305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.011847,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001756,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
275414,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000047,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276538,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000734,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.011152,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277478,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006771,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
others_similarity1 = pd.DataFrame(
    {
        'user-1' : others_similarity.idxmax().index,
        'user-2' : others_similarity.idxmax().values
    }
)

others_similarity1

     user-1  user-2
0       183  261379
1      1903   38281
2      2442   26813
3      3757  131126
4      5903   27788
..      ...     ...
260  274111   70999
261  275414   29117
262  276538   11676
263  276925   81207
264  277478  199092

[265 rows x 2 columns]

### Creating Function

In [ ]:
def create_result(s,x):
    ISBN = []
    rating = []

    for i in s[s['user-2'] == x].loc[:,'user-1']:
        for j in area[(area['User-ID'] == i)].index:
            k = area.loc[j,'ISBN']
            l = area.loc[j,'Book-Rating']
            ISBN.append(k)
            rating.append(l)

    result = pd.DataFrame(
        {
            'ISBN' : ISBN,
            'rating' : rating
        }
    )

    return result

In [ ]:
def get_ISBN(x):
    d = []
    for i in area[(area['User-ID'] == x)].loc[:,'ISBN'].values:
        d.append(i)
    
    return d

In [ ]:
def drop(a,b):

    drop = []

    for i in range(len(a)):
        for j in b:
            c = a.loc[i,'ISBN']
            if c == j:
                drop.append(i)

    return drop

In [ ]:
def fillter_ISBN(x, y):

    x.drop(index=y, inplace= True)
    x.drop_duplicates(inplace=True)

    return x

In [ ]:
def predect_by_area(similarity,ISBN):

    o = create_result(similarity,ISBN)
    k = get_ISBN(ISBN)
    n = drop(o,k)
    e = fillter_ISBN(o,n)

    return e.sort_values(by='rating', ascending= False).head(5)

In [ ]:
predect_by_area(others_similarity1,199092)

           ISBN  rating
15   0099468239      10
308  0810945797      10
314  0831759267      10
297  0752524593      10
44   0375713301       9